### ISSUE TITLE
a community testnet defiads node

### ISSUE THREAD

**Issue by philbertw4** [defiads/defiads#13]
I started setting up a defiads server (using the wonderful https://bitclouds.sh service) so that there will at least be an always-on testnet server for us to connect to.

Unfortunately, there seems to be something broken that I am having a hard time debugging.

```
defiads@alphard:~/defiads$ target/release/defiads --log-level TRACE &
[1] 20739
defiads@alphard:~/defiads$ Starting defiads, connected to testnet network.
Observe progress in the log file: /home/defiads/.defiads/testnet/defiads.log
Warnings and errors will be also printed to stderr.

defiads@alphard:~/defiads$ tail -f ~/.defiads/testnet/defiads.log 
23:58:37 [ INFO] Wallet balance: 0 satoshis 0 available
23:58:37 [ INFO] reaching out for DNS seed...
23:58:37 [TRACE] (13) mio::poll: [/home/defiads/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:787] registering with poller
23:58:37 [TRACE] (13) mio::poll: [/home/defiads/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:787] registering with poller
23:58:37 [TRACE] (14) mio::poll: [/home/defiads/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:787] registering with poller
23:58:37 [ INFO] received 114 DNS seeds
23:58:37 [ INFO] reaching out for defiads seed...
23:58:37 [ INFO] received 0 defiads seeds
23:58:37 [TRACE] (17) mio::poll: [/home/defiads/.cargo/registry/src/github.com-1ecc6299db9ec823/mio-0.6.19/src/poll.rs:787] registering with poller
23:58:37 [ INFO] listen to 0.0.0.0:21866
23:59:38 [ WARN] can not poll content as no defiads peers are connected
```

Normally (for example, when running this on a laptop), the `tail -f ` command shows that there is a lot of activity as the SPV node comes into sync with the bitcoin network. Yet, for some reason it seems to be stalled. 

I know next to nothing about rust and the underlying bitcoin-rust toolchain that is being used here. Any ideas/help is much welcome!

**Comment by philbertw4** [comment]
As a quick followup, there is a chance that this is not a rust issue or a defiads issue, but instead a sysadmin issue. It seems quite odd though that the syncing process works fine on a laptop but not on a brand new VPS.

**Comment by philbertw4** [comment]
also, for additional reference, here is some output that is seen when running the same commands on a laptop. Hope it is helpful:
```
00:17:58 [ INFO] new chain tip at height 1607065 00000000000002c2e81cea77828f9961785e7fb509c9eedfbd535350b175954c
00:17:58 [ INFO] new chain tip at height 1607066 00000000000002ed14479898efc958ceb8c4b2b8df8b0d1c0b00b8da0392f7c3
00:17:58 [ INFO] new chain tip at height 1607067 000000000000032dd607b522d5226455d1005ae5ff00ecfe19ad3ace5758c4e6
00:17:58 [ INFO] received 1067 headers new tip=000000000000032dd607b522d5226455d1005ae5ff00ecfe19ad3ace5758c4e6 from peer=bitcoin-3
00:18:22 [DEBUG] (18) defiads::blockdownload: asked 138 blocks from peer=bitcoin-1
00:18:23 [DEBUG] (18) defiads::store: processing block 1606930 00000000000b45d796e8fa0d5a3232c21559c7121d11ac6902e3f714513fc95b
00:18:23 [DEBUG] (18) defiads::blockdownload: still waiting for blocks from peer=bitcoin-1
00:18:23 [DEBUG] (18) defiads::store: processing block 1606931 00000000000001fbfc139b3a18b3f92aadefd9eda4d54b4d8d6b819c1f732ee0
00:18:23 [DEBUG] (18) defiads::blockdownload: still waiting for blocks from peer=bitcoin-1
00:18:23 [DEBUG] (18) defiads::store: processing block 1606932 0000000000000377a4af79b8ddfac887249a84d17d0e8b25aabdbd2239a15408
00:18:23 [DEBUG] (18) defiads::blockdownload: still waiting for blocks from peer=bitcoin-1
00:18:23 [DEBUG] (18) defiads::store: processing block 1606933 0000000000000365188883daec6dca9191aef41e5ddf5f7ae3d965fbbdc293b8
00:18:23 [DEBUG] (18) defiads::blockdownload: still waiting for blocks from peer=bitcoin-1
00:18:23 [DEBUG] (18) defiads::store: processing block 1606934 000000000000034fb0b9bd384bf380625169838f18ea9a04e69392a7257f5ea1
00:18:23 [DEBUG] (18) defiads::blockdownload: still waiting for blocks from peer=bitcoin-1
00:18:23 [DEBUG] (18) defiads::store: processing block 1606935 00000000000003cfef75315b343f9279391385015eea6b644f7bc182b774fdf3
```
Note that the SPV syncing process is progressing whereas in the VPS it seems stalled :-/

**Comment by philbertw4** [comment]
Still attempting to resolve this issue. I tried to revert back to the release that was tagged 0.1.0, and the same problem persists. I'll try downgrading rust next to match the version on the laptop (where defiads does appear to work). If the issue persists, then it must, or so it seems, be some failure in sysadmin skills on my part, such as needing to manually open some ports?

**Comment by philbertw4** [comment]
Ok, neither of the above two things fixed the issue. Additionally setting `ufw` firewall policies to allow the appropriate ports did not help.
```
To                         Action      From
--                         ------      ----
22/tcp                     ALLOW IN    Anywhere                  
18333/tcp                  ALLOW IN    Anywhere                  
21866/tcp                  ALLOW IN    Anywhere                  
22/tcp (v6)                ALLOW IN    Anywhere (v6)             
18333/tcp (v6)             ALLOW IN    Anywhere (v6)             
21866/tcp (v6)             ALLOW IN    Anywhere (v6) 
```
I've also tried this on two different VPS providers now, so the problem does not seem specific to a particular VPS provider.

**Comment by philbertw4** [comment]
Long day's journey into night and I think I may have (partially) resolved this issue. For lack of anything else to try, and not knowing enough bout rust to profile things, I wondered if the VPS simply didn't have enough memory. So, after trying to run at test defiads server on a VPS with 8gb of memory (as opposed to 1gb and 2gb that were available on the other VPS instances I was trying), and alas, it seems to be working.

So, while I have no idea what the "bare minimum" memory requirements are for defiads right now, it does seem that having a server with 8gb of memory seems to be enough.

I'll work on getting a publicly accessible testnet server up and running for us and will close this issue (and submit updates to the documentation) once it has been done.

**Comment by philbertw4** [comment]
Ok, we now have a community testnet server thanks to a slightly custom setup from the people at bitclouds.sh

If you choose to run a defiads node, please follow the instructions in the README.md file and run the node with the command `target/release/defiads --defiads-peers 188.165.223.61:21866` as this will instruct your node to reach out to the community testnet node for syncing.

If you would like to help support the operation of the server, you can query how much time the server has been funded for by taking the following steps:
1. `curl https://bitclouds.sh/status/avior-1` this will tell you how much time remains before the server will be decommissioned.
2. `curl https://bitclouds.sh/topup/avior-1/10000` will provide you with an invoice for 10,000 satoshis. When paid, more time will be bought for the server (current prices are approx 66 satoshis/hr).
3. re-run `curl https://bitclouds.sh/status/avior-1` to see the that the time remaining has been increased.
4. Thanks!

**Comment by philbertw4** [comment]
Did anyone find it helpful to have this community testing server (running on bitcoin's testnet3) available?  It's been a while since I have had a chance to look at defiads and it seems that this server has since died (funds for its instance on bitclouds.sh ran out).

**Comment by ZmnSCPxj** [comment]
An alternative would be to  use some other discovery method, such as DNS as used by Bitcoin and Lightning, or IRC as used by JoinMarket (and [Lightning a long time ago](https://github.com/lightningnetwork/lightning-rfc/blob/2aa9f971afab7ac1085f8fe21c27dc64dc76edaf/06-irc-announcements.md), why do you think there is no BOLT 6 now?).

Of course, this still requires some central server *somewhere* to bootstrap the network.  If we can get Tor integration so that defiads can run behind a Tor hidden service I can run a defiads node myself for this purpose, but from what I can tell, there is no Tor integration yet.

**Comment by philbertw4** [comment]
Good points, and yes, for a variety of reasons, we try to get defiads capable of operating behind a Tor hidden service sooner than later. I will close this issue for now so nobody is confused about the now-defunct community server.
