### ISSUE TITLE
trouble connecting to defiads testnet?

### ISSUE THREAD

**Issue by philbertw4** [defiads/defiads#3]
This is exciting times and great work. Kudos to @tamasblummer for getting defiads underway!

Opening this issue in case anyone else has the same problem. When following the instructions in the readme, it is relatively easy to get everything "working." However, it seems that peer discovery is not yet implemented yet. Therefore one may end up with output similar to:

```
23:34:45 [ WARN] can not poll content as no defiads peers are connected
23:35:46 [ WARN] can not poll content as no defiads peers are connected
23:36:47 [ WARN] can not poll content as no defiads peers are connected
23:37:48 [ WARN] can not poll content as no defiads peers are connected
23:38:49 [ WARN] can not poll content as no defiads peers are connected
23:39:50 [ WARN] can not poll content as no defiads peers are connected
23:40:51 [ WARN] can not poll content as no defiads peers are connected
23:41:52 [ WARN] can not poll content as no defiads peers are connected
```

This is because we apparently need to be using the option `—defiads-peers [ADDRESS]` where ADDRESS is replaced by the address of a peer to connect to. Unfortunately, I'm not sure how to resolve this and try out the software, as I do not know of another address to connect to at the moment. @tamasblummer are you running a node that we can connect to so that we can try it out?

Alternatively, if you suggest that we try things out solely locally first via regtest, is there some instructions you can provide to help us along with that?

**Comment by tamasblummer** [comment]
Yes, the warning is because the node has no peers. There is no discovery mechanism implemented yet and --defiads-peers have to be used to connect to some others. The nodes propagate addresses they learned, so you only have to find one to discover the rest of the network. At the moment however I am not aware of a network. Send me a mail, so I send you my node's address: tamas.blummer@protonmail.com

**Comment by philbertw4** [comment]
@tamasblummer Thanks for this information. It is helpful. One other question follows (which could be because I'm new to the Rust ecosystem and still trying to figure it out): currently the only way to test functionality of defiads is via testnet (bitcoin's testnet3). Therefore, if there are no defiads peers online to connect to, we need to run two local testnet peers if we want to test out publishing/reading of an ad. Is that correct?

For example, I tried to run it with `--bitcoin-network regtest` but was given the following:
```
target/release/defiads --bitcoin-network regtest
error: 'regtest' isn't a valid value for '--bitcoin-network <NETWORK>'
	[possible values: bitcoin, testnet]


USAGE:
    defiads --bitcoin-connections <n> --bitcoin-discovery <bitcoin-discovery> --bitcoin-network <NETWORK> --defiads-connections <n> --defiads-discovery <defiads-discovery> --http-rpc <ADDRESS> --listen <ADDRESS>... --log-level <LEVEL> --storage-limit <n>
```
When you're doing your development/testing, are you doing it like above and running multiple local nodes that are communicating via actual bitcoin testnet3, or do somehow you have a local `regtest` type network working somehow?

**Comment by tamasblummer** [comment]
I pushed a commit to enable regtest. Multiple connects from same IP are possible now, which may cause some noise the nodes trying to re-connect to themselves. Will fix that later.

**Comment by jonasnick** [comment]
>  There is no discovery mechanism implemented yet and --defiads-peers have to be used to connect to some others. 

Perhaps the README could mention that this argument is required.
