### ISSUE TITLE
disconnected after trying to read ad

### ISSUE THREAD

**Issue by philbertw4** [defiads/defiads#4]
I managed to publish a first ad on defiads! I was then able to use the curl calls to list the categories, and then traverse into the category ("misc" in this case) and find my ad. However, when I tried to use the command to read the add, I ended up with this error (from the log):

```
23:43:29 [DEBUG] (22) rpc: Response: {"jsonrpc":"2.0","result":[["367c5219c47b14a47019b6d0ede8f9005fef10819853726d161c4c4d8581c0c0","misc","Defiads is alive!"]],"id":1}.
23:43:35 [ERROR] thread 'jsonrpc-eventloop-1' panicked at 'called `Result::unwrap()` on an `Err` value: Base58(InvalidLength(35))': src/libcore/result.rs:999
23:43:35 [ERROR] thread 'futures 4' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"': src/libcore/result.rs:999
23:43:35 [ERROR] thread 'futures 3' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"': src/libcore/result.rs:999
23:43:56 [ERROR] thread 'sendtx' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"': src/libcore/result.rs:999
23:43:56 [ERROR] thread 'dispatcher' panicked at 'P2P message send failed: "SendError(..)"': src/libcore/result.rs:999
23:43:56 [ERROR] thread 'futures 0' panicked at 'P2P message send failed: "SendError(..)"': src/libcore/result.rs:999
23:43:56 [ERROR] thread 'discovery' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"': src/libcore/result.rs:999
23:43:56 [ WARN] can not poll content as no defiads peers are connected
23:44:29 [ERROR] thread 'jsonrpc-eventloop-1' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"': src/libcore/result.rs:999
```

I figured that perhaps my parameters for the `read` command were wrong. However, strangely, after this incident when I ran `categories` and `list` again, curl returned `(52) Empty reply from server.`

**Comment by tamasblummer** [comment]
Hi @philbertw4,
thanks for reporting this. This was a formatting bug in storage of content, fixed with https://github.com/defiads/defiads/commit/689f224d0ad0acdfba59e56d4b1de88c5b6bb3ea

Please recompile. That ad will remain unreadable.

Once an [ERROR] is reported esp. with 'panicked' then the process is likely severely damaged and should be restarted as it will no longer produce meaningful output.
