### ISSUE TITLE
Can't Install Defiads, Error Related to C++

### ISSUE THREAD

**Issue by dmar198** [defiads/defiads#9]
I tried to compile defiads today. When I got to cargo build --release it began compiling various things and then broke at this point:

-------- Begin code --------

   Compiling aho-corasick v0.7.6
   Compiling futures-util-preview v0.3.0-alpha.18
   Compiling bstr v0.2.8
error: failed to run custom build command for `bitcoinconsensus v0.17.1`

Caused by:
  process didn't exit successfully: `/home/[blocked-for-privacy]/defiads/target/release/build/bitcoinconsensus-92955efa0baa0f53/build-script-build` (exit code: 1)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "c++" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "bitcoin/src" "-I" "bitcoin/src/secp256k1/include" "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-D__STDC_FORMAT_MACROS" "-o" "/home/[blocked-for-privacy]/defiads/target/release/build/bitcoinconsensus-64a41d0281aadc9e/out/bitcoin/src/utilstrencodings.o" "-c" "bitcoin/src/utilstrencodings.cpp"

--- stderr

error occurred: Failed to find tool. Is `c++` installed?

warning: build failed, waiting for other jobs to finish...
error: build failed

-------- End of code --------

I have g++ installed. Am I supposed to have something else installed to make c++ work?

**Comment by ZmnSCPxj** [comment]
Most distros will alias `c++` to `g++` if installed, or maybe you need to run `update-alternatives` and select for `c++` what `g++` will be, what is your distro?

**Comment by dmar198** [comment]
My distro is debian stretch. The problem was that I was wrong -- I did not have g++ installed. This issue can be closed.
